### ISSUE TITLE
Log problème Python

### ISSUE THREAD

**Issue by w-mos** [igocreate/igo#14]
`4101 info run fibers@5.0.0 install node_modules/fibers node build.js || nodejs build.js

4102 info run sharp@0.29.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
4103 info run fibers@5.0.0 install { code: 1, signal: null }
4104 info run sharp@0.29.3 install { code: 1, signal: null }
4105 warn cleanup Failed to remove some directories [
4105 warn cleanup   [
4105 warn cleanup     'D:\\Development\\Website\\igocreate\\node_modules\\sharp',
4105 warn cleanup     [Error: EBUSY: resource busy or locked, rmdir 'D:\Development\Website\igocreate\node_modules\sharp'] {
4105 warn cleanup       errno: -4082,
4105 warn cleanup       code: 'EBUSY',
4105 warn cleanup       syscall: 'rmdir',
4105 warn cleanup       path: 'D:\\Development\\Website\\igocreate\\node_modules\\sharp'
4105 warn cleanup     }
4105 warn cleanup   ]
4105 warn cleanup ]
4106 timing reify:rollback:createSparse Completed in 2999ms
4107 timing reify:rollback:retireShallow Completed in 0ms
4108 timing command:install Completed in 15814ms
4109 verbose stack Error: command failed
4109 verbose stack     at ChildProcess.<anonymous> (C:\Users\wmost\AppData\Local\pnpm\nodejs\16.13.1\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
4109 verbose stack     at ChildProcess.emit (node:events:390:28)
4109 verbose stack     at maybeClose (node:internal/child_process:1064:16)
4109 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
4110 verbose pkgid fibers@5.0.0
4111 verbose cwd D:\Development\Website\igocreate
4112 verbose Windows_NT 10.0.22000
4113 verbose argv "C:\\Users\\wmost\\AppData\\Local\\pnpm\\node.exe" "C:\\Users\\wmost\\AppData\\Local\\pnpm\\nodejs\\16.13.1\\node_modules\\npm\\bin\\npm-cli.js" "i" "igo" "mocha"
4114 verbose node v16.13.1
4115 verbose npm  v8.1.2
4116 error code 1
4117 error path D:\Development\Website\igocreate\node_modules\fibers
4118 error command failed
4119 error command C:\Windows\system32\cmd.exe /d /s /c node build.js || nodejs build.js
4120 error gyp info it worked if it ends with ok
4120 error gyp info using node-gyp@8.3.0
4120 error gyp info using node@16.13.1 | win32 | x64
4120 error gyp ERR! find Python
4120 error gyp ERR! find Python Python is not set from command line or npm configuration
4120 error gyp ERR! find Python Python is not set from environment variable PYTHON
4120 error gyp ERR! find Python checking if "python3" can be used
4120 error gyp ERR! find Python - "python3" is not in PATH or produced an error
4120 error gyp ERR! find Python checking if "python" can be used
4120 error gyp ERR! find Python - "python" is not in PATH or produced an error
4120 error gyp ERR! find Python checking if Python is C:\Users\wmost\AppData\Local\Programs\Python\Python39\python.exe
4120 error gyp ERR! find Python - "C:\Users\wmost\AppData\Local\Programs\Python\Python39\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
4120 error gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Users\wmost\AppData\Local\Programs\Python\Python39-32\python.exe
4120 error gyp ERR! find Python - "C:\Users\wmost\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
4120 error gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
4120 error gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Users\wmost\AppData\Local\Programs\Python\Python38\python.exe
4120 error gyp ERR! find Python - "C:\Users\wmost\AppData\Local\Programs\Python\Python38\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
4120 error gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Users\wmost\AppData\Local\Programs\Python\Python38-32\python.exe
4120 error gyp ERR! find Python - "C:\Users\wmost\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
4120 error gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
4120 error gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Users\wmost\AppData\Local\Programs\Python\Python37\python.exe
4120 error gyp ERR! find Python - "C:\Users\wmost\AppData\Local\Programs\Python\Python37\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
4120 error gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Users\wmost\AppData\Local\Programs\Python\Python37-32\python.exe
4120 error gyp ERR! find Python - "C:\Users\wmost\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
4120 error gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
4120 error gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Users\wmost\AppData\Local\Programs\Python\Python36\python.exe
4120 error gyp ERR! find Python - "C:\Users\wmost\AppData\Local\Programs\Python\Python36\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
4120 error gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Users\wmost\AppData\Local\Programs\Python\Python36-32\python.exe
4120 error gyp ERR! find Python - "C:\Users\wmost\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
4120 error gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
4120 error gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
4120 error gyp ERR! find Python checking if the py launcher can be used to find Python 3
4120 error gyp ERR! find Python - "py.exe" is not in PATH or produced an error
4120 error gyp ERR! find Python
4120 error gyp ERR! find Python **********************************************************
4120 error gyp ERR! find Python You need to install the latest version of Python.
4120 error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
4120 error gyp ERR! find Python you can try one of the following options:
4120 error gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
4120 error gyp ERR! find Python   (accepted by both node-gyp and npm)
4120 error gyp ERR! find Python - Set the environment variable PYTHON
4120 error gyp ERR! find Python - Set the npm configuration variable python:
4120 error gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
4120 error gyp ERR! find Python For more information consult the documentation at:
4120 error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
4120 error gyp ERR! find Python **********************************************************
4120 error gyp ERR! find Python
4120 error gyp ERR! configure error
4120 error gyp ERR! stack Error: Could not find any Python installation to use
4120 error gyp ERR! stack     at PythonFinder.fail (C:\Users\wmost\AppData\Local\pnpm\nodejs\16.13.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:330:47)
4120 error gyp ERR! stack     at PythonFinder.runChecks (C:\Users\wmost\AppData\Local\pnpm\nodejs\16.13.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:159:21)
4120 error gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\wmost\AppData\Local\pnpm\nodejs\16.13.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:228:18)
4120 error gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\wmost\AppData\Local\pnpm\nodejs\16.13.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:294:16)
4120 error gyp ERR! stack     at exithandler (node:child_process:404:5)
4120 error gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:416:5)
4120 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
4120 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
4120 error gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
4120 error gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
4120 error gyp ERR! System Windows_NT 10.0.22000
4120 error gyp ERR! command "C:\\Users\\wmost\\AppData\\Local\\pnpm\\node.exe" "C:\\Users\\wmost\\AppData\\Local\\pnpm\\nodejs\\16.13.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
4120 error gyp ERR! cwd D:\Development\Website\igocreate\node_modules\fibers
4120 error gyp ERR! node -v v16.13.1
4120 error gyp ERR! node-gyp -v v8.3.0
4120 error gyp ERR! not ok
4120 error node-gyp exited with code: 1
4120 error Please make sure you are using a supported platform and node version. If you
4120 error would like to compile fibers on this machine please make sure you have setup your
4120 error build environment--
4120 error Windows + OS X instructions here: https://github.com/nodejs/node-gyp
4120 error Ubuntu users please run: `sudo apt-get install g++ build-essential`
4120 error RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
4120 error Alpine users please run: `sudo apk add python make g++`
4120 error 'nodejs' n'est pas reconnu en tant que commande interne
4120 error ou externe, un programme ex�cutable ou un fichier de commandes.
4121 verbose exit 1`

**Comment by w-mos** [comment]
[2022-01-24T12_40_09_815Z-debug.log](https://github.com/igocreate/igo/files/7925975/2022-01-24T12_40_09_815Z-debug.log)

**Comment by w-mos** [comment]
Hello ! It was already on npm, the problem was solely on node-gyp finally, which have to be installed before all others dependencies.
